# Generated by Django 3.0.8 on 2020-07-14 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=100)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_time', models.IntegerField()),
                ('task_name', models.CharField(max_length=100)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('task_description', models.TextField()),
                ('subcategory', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_time_start', models.DateTimeField()),
                ('session_time_end', models.DateTimeField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('session_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LongRest',
            fields=[
                ('rest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usersessions.Rest')),
                ('long_rest_time', models.IntegerField()),
            ],
            bases=('usersessions.rest',),
        ),
        migrations.CreateModel(
            name='ShortRest',
            fields=[
                ('rest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usersessions.Rest')),
                ('short_rest_time', models.IntegerField()),
            ],
            bases=('usersessions.rest',),
        ),
    ]
