# Generated by Django 3.0.8 on 2020-07-14 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersessions', '0002_usersession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='usersession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usersessions.UserSession'),
        ),
        migrations.AddField(
            model_name='task',
            name='usersession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usersessions.UserSession'),
        ),
    ]
