# Generated by Django 3.0.8 on 2020-07-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersessions', '0003_auto_20200714_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subcategory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_time_end',
            field=models.DateTimeField(null=True),
        ),
    ]
