# Generated by Django 3.0.8 on 2020-07-23 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersessions', '0004_auto_20200719_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rest',
            name='usersession',
        ),
        migrations.RemoveField(
            model_name='shortrest',
            name='rest_ptr',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='subcategory',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_description',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='category',
        ),
        migrations.DeleteModel(
            name='LongRest',
        ),
        migrations.DeleteModel(
            name='Rest',
        ),
        migrations.DeleteModel(
            name='ShortRest',
        ),
    ]
