# Generated by Django 3.0.8 on 2020-07-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200727_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='award4',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='award5',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='award1',
            field=models.IntegerField(choices=[(0, 'empty_plate'), (1, 'tomato_basil_spaghetti'), (2, 'tomato_lasagna'), (3, 'tomato_pizza'), (4, 'tomato_sauce_penne'), (5, 'tomato_sauce_spaghetti')], default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='award2',
            field=models.IntegerField(choices=[(0, 'empty_plate'), (1, 'tomato_basil_spaghetti'), (2, 'tomato_lasagna'), (3, 'tomato_pizza'), (4, 'tomato_sauce_penne'), (5, 'tomato_sauce_spaghetti')], default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='award3',
            field=models.IntegerField(choices=[(0, 'empty_plate'), (1, 'tomato_basil_spaghetti'), (2, 'tomato_lasagna'), (3, 'tomato_pizza'), (4, 'tomato_sauce_penne'), (5, 'tomato_sauce_spaghetti')], default=0),
        ),
    ]
